<a href="https://colab.research.google.com/github/HimanshuSahoo/NLP/blob/main/8_Word_Embedding_Techniques_using_Embedding_Layer_in_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### Vocabulary size
voc_size=10000

### One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[3413, 1124, 1173, 1365], [3413, 1124, 1173, 9921], [3413, 1177, 1173, 3486], [8541, 6160, 9131, 713, 766], [8541, 6160, 9131, 713, 9028], [614, 3413, 4416, 1173, 5365], [8933, 8944, 5919, 713]]


## Word Embedding Represntation

In [ ]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:

import numpy as np

In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3413 1124 1173 1365]
 [   0    0    0    0 3413 1124 1173 9921]
 [   0    0    0    0 3413 1177 1173 3486]
 [   0    0    0 8541 6160 9131  713  766]
 [   0    0    0 8541 6160 9131  713 9028]
 [   0    0    0  614 3413 4416 1173 5365]
 [   0    0    0    0 8933 8944 5919  713]]


In [ ]:
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:

print(model.predict(embedded_docs))

[[[ 0.0197933  -0.02689885 -0.03621082  0.04300443  0.04221226
    0.01665271  0.04497739 -0.03876468 -0.02553158  0.04983116]
  [ 0.0197933  -0.02689885 -0.03621082  0.04300443  0.04221226
    0.01665271  0.04497739 -0.03876468 -0.02553158  0.04983116]
  [ 0.0197933  -0.02689885 -0.03621082  0.04300443  0.04221226
    0.01665271  0.04497739 -0.03876468 -0.02553158  0.04983116]
  [ 0.0197933  -0.02689885 -0.03621082  0.04300443  0.04221226
    0.01665271  0.04497739 -0.03876468 -0.02553158  0.04983116]
  [ 0.00113409  0.01825139 -0.03257138 -0.0053452   0.01150692
   -0.03097271  0.02958026  0.02321887 -0.04479864  0.01717037]
  [ 0.01984546 -0.02838538 -0.04843804  0.00646086 -0.02219482
    0.04436048  0.01707807  0.04182783 -0.00153871 -0.01659968]
  [ 0.02608115  0.02605848 -0.04114072  0.04772169 -0.02876074
   -0.01206248 -0.00211289 -0.01598573 -0.04912417  0.01488233]
  [-0.0282665  -0.01919551 -0.00017099  0.01590453 -0.04399663
    0.04252619 -0.00362802  0.02482602  0.018014

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 3413, 1124, 1173, 1365])

In [ ]:
print(model.predict(embedded_docs)[0])

[[ 0.0197933  -0.02689885 -0.03621082  0.04300443  0.04221226  0.01665271
   0.04497739 -0.03876468 -0.02553158  0.04983116]
 [ 0.0197933  -0.02689885 -0.03621082  0.04300443  0.04221226  0.01665271
   0.04497739 -0.03876468 -0.02553158  0.04983116]
 [ 0.0197933  -0.02689885 -0.03621082  0.04300443  0.04221226  0.01665271
   0.04497739 -0.03876468 -0.02553158  0.04983116]
 [ 0.0197933  -0.02689885 -0.03621082  0.04300443  0.04221226  0.01665271
   0.04497739 -0.03876468 -0.02553158  0.04983116]
 [ 0.00113409  0.01825139 -0.03257138 -0.0053452   0.01150692 -0.03097271
   0.02958026  0.02321887 -0.04479864  0.01717037]
 [ 0.01984546 -0.02838538 -0.04843804  0.00646086 -0.02219482  0.04436048
   0.01707807  0.04182783 -0.00153871 -0.01659968]
 [ 0.02608115  0.02605848 -0.04114072  0.04772169 -0.02876074 -0.01206248
  -0.00211289 -0.01598573 -0.04912417  0.01488233]
 [-0.0282665  -0.01919551 -0.00017099  0.01590453 -0.04399663  0.04252619
  -0.00362802  0.02482602  0.01801449  0.00216322]]